"""Caduceus database module."""

from caduceus.db.queries import (
    init_db,
    create_task,
    get_task,
    update_task,
    start_task,
    complete_task,
    fail_task,
    get_pending_tasks,
    get_tasks_by_status,
    get_tasks_by_project,
    list_tasks,
    assign_task,
    register_agent,
    get_agent,
    update_agent,
    set_agent_busy,
    set_agent_idle,
    set_agent_error,
    refresh_heartbeat,
    list_agents,
    get_idle_agents,
    create_execution,
    complete_execution,
    get_execution,
    get_task_executions,
    create_trigger,
    get_trigger,
    update_trigger,
    get_enabled_triggers,
    delete_trigger,
    create_approval,
    get_approval,
    resolve_approval,
    get_pending_approvals,
    get_stats,
)

__all__ = [
    "init_db",
    "create_task", "get_task", "update_task", "start_task",
    "complete_task", "fail_task", "get_pending_tasks",
    "get_tasks_by_status", "get_tasks_by_project", "list_tasks",
    "assign_task",
    "register_agent", "get_agent", "update_agent",
    "set_agent_busy", "set_agent_idle", "set_agent_error",
    "refresh_heartbeat", "list_agents", "get_idle_agents",
    "create_execution", "complete_execution", "get_execution",
    "get_task_executions",
    "create_trigger", "get_trigger", "update_trigger",
    "get_enabled_triggers", "delete_trigger",
    "create_approval", "get_approval", "resolve_approval",
    "get_pending_approvals",
    "get_stats",
]
